package br.ufal.ic.repo.model;

/**
 *
 * @author marcos
 */
public enum ChangeType {
    ADDED, BODY_MODIFIED, CHANGED_RETURN_TYPE, DELETED, INCREASED_VISIBILITY, 
    PARAMETER_ADDED, PARAMETER_REMOVED, REMOVED_THROWN_EXCEPTION, RENAMED, 
    REDUCED_VISIBILITY, THROWS_NEW_EXCEPTIONS
}
